### ISSUE TITLE
More details needed from Conviva error reporting

### ISSUE THREAD

**Issue by dyue** [bitmovin/bitmovin-player-android-analytics-conviva#49]
The add-on is reporting player error to Conviva.  However, from time to time, the error message is extremely terse, like "General - A general error occurred:", with no text after the colon.

The error is likely reported here in [ConvivaAnalyticsIntegration class](https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/blob/4ad149f03dad134de3aaefbd3c070365b9031ccf/conviva/src/main/java/com/bitmovin/analytics/conviva/ConvivaAnalyticsIntegration.java#L413):
```
            String message = String.format("%s - %s", event.getCode(), event.getMessage());
            convivaVideoAnalytics.reportPlaybackError(message, ConvivaSdkConstants.ErrorSeverity.FATAL);
```

Since the error event does have a data field, would it be possible to give some details from the data field too?

This is a screenshot of the reporting in Conviva dashboard:
![Screen Shot 2023-03-29 at 1 55 48 PM](https://user-images.githubusercontent.com/2789777/228665552-e891858f-84da-4b25-a9bc-03f620253315.png)

**Comment by LudoMichaud** [comment]
@dyue do you know on which platforms you are observing this behaviour ? (eg. do you see this mostly on iOS/Safari or iOS/Native for instance) ?  
It could be that the underlaying Native platform (eg. the native player of Safari for instance) doesn't return enough information in order for the player to surface a more detailed error message. 

At this point, I believe this is not a Conviva integration issue, but rather a player question. I will therefore close this ticket for now and follow up on the ticket you just opened (16034). Let's reopen this issue in case it turns out to be related to conviva.
